title: AllenNLP NER algo for Acharya
owner: Phonemonk
author: Phonemonk
train:
        cmd: allennlp train testNERconfig.json -s output/crf_model
        type: cmd
        input: data/trainfile.conll
        output: stdout
eval:
        cmd: python eval_allennlp_to_conll2003.py /tmp/out
        type: cmd
        input: data/infile.conll
        output: stdout

